// <auto-generated />
using System;
using MessManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessManagement.Migrations
{
    [DbContext(typeof(MessDbContext))]
    [Migration("20251214120159_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BreakfastPresent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DinnerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("LunchPresent")
                        .HasColumnType("bit");

                    b.Property<int>("MarkedBy")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarkedBy");

                    b.HasIndex("MemberId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("MessManagement.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("RoomNumber");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MessManagement.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MessManagement.Models.WaterTea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("TeaCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WaterCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "Date")
                        .IsUnique();

                    b.ToTable("WaterTeaRecords");
                });

            modelBuilder.Entity("MessManagement.Models.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek", "MealType");

                    b.ToTable("WeeklyMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(5829),
                            DayOfWeek = "Monday",
                            DishName = "Rice with Dal",
                            MealType = "Lunch",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7965),
                            DayOfWeek = "Monday",
                            DishName = "Roti with Sabzi",
                            MealType = "Dinner",
                            Price = 45m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7970),
                            DayOfWeek = "Tuesday",
                            DishName = "Biryani",
                            MealType = "Lunch",
                            Price = 80m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7972),
                            DayOfWeek = "Tuesday",
                            DishName = "Chapati with Curry",
                            MealType = "Dinner",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7974),
                            DayOfWeek = "Wednesday",
                            DishName = "Fried Rice",
                            MealType = "Lunch",
                            Price = 60m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7981),
                            DayOfWeek = "Wednesday",
                            DishName = "Paratha with Curd",
                            MealType = "Dinner",
                            Price = 55m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7983),
                            DayOfWeek = "Thursday",
                            DishName = "Paneer Curry with Rice",
                            MealType = "Lunch",
                            Price = 75m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7984),
                            DayOfWeek = "Thursday",
                            DishName = "Khichdi",
                            MealType = "Dinner",
                            Price = 40m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7986),
                            DayOfWeek = "Friday",
                            DishName = "Chicken Curry",
                            MealType = "Lunch",
                            Price = 100m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7989),
                            DayOfWeek = "Friday",
                            DishName = "Egg Curry with Rice",
                            MealType = "Dinner",
                            Price = 70m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7990),
                            DayOfWeek = "Saturday",
                            DishName = "Special Thali",
                            MealType = "Lunch",
                            Price = 120m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7992),
                            DayOfWeek = "Saturday",
                            DishName = "Pulao",
                            MealType = "Dinner",
                            Price = 65m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7994),
                            DayOfWeek = "Sunday",
                            DishName = "Fish Curry",
                            MealType = "Lunch",
                            Price = 110m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 14, 12, 1, 55, 607, DateTimeKind.Utc).AddTicks(7995),
                            DayOfWeek = "Sunday",
                            DishName = "Mixed Veg Rice",
                            MealType = "Dinner",
                            Price = 55m
                        });
                });

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.HasOne("MessManagement.Models.User", "MarkedByUser")
                        .WithMany()
                        .HasForeignKey("MarkedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkedByUser");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagement.Models.Member", b =>
                {
                    b.HasOne("MessManagement.Models.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("MessManagement.Models.Member", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.PasswordResetToken", b =>
                {
                    b.HasOne("MessManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagement.Models.WaterTea", b =>
                {
                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany("WaterTeaRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagement.Models.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");

                    b.Navigation("WaterTeaRecords");
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
