// <auto-generated />
using System;
using MessManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessManagement.Migrations
{
    [DbContext(typeof(MessDbContext))]
    partial class MessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BreakfastPresent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DinnerPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("LunchPresent")
                        .HasColumnType("bit");

                    b.Property<int>("MarkedBy")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MarkedBy");

                    b.HasIndex("MemberId", "Date")
                        .IsUnique();

                    b.ToTable("Attendances", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("RoomNumber");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("MemberId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.Suggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionId"));

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RespondedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SuggestionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MemberId");

                    b.HasIndex("RespondedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("Suggestions", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.WaterTea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("TeaCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WaterCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "Date")
                        .IsUnique();

                    b.ToTable("WaterTeaRecords", (string)null);
                });

            modelBuilder.Entity("MessManagement.Models.WeeklyMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("MenuDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek", "MealType");

                    b.ToTable("WeeklyMenus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 926, DateTimeKind.Utc).AddTicks(8124),
                            DayOfWeek = "Monday",
                            DishName = "Rice with Dal",
                            MealType = "Lunch",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2674),
                            DayOfWeek = "Monday",
                            DishName = "Roti with Sabzi",
                            MealType = "Dinner",
                            Price = 45m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2684),
                            DayOfWeek = "Tuesday",
                            DishName = "Biryani",
                            MealType = "Lunch",
                            Price = 80m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2687),
                            DayOfWeek = "Tuesday",
                            DishName = "Chapati with Curry",
                            MealType = "Dinner",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2689),
                            DayOfWeek = "Wednesday",
                            DishName = "Fried Rice",
                            MealType = "Lunch",
                            Price = 60m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2835),
                            DayOfWeek = "Wednesday",
                            DishName = "Paratha with Curd",
                            MealType = "Dinner",
                            Price = 55m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2838),
                            DayOfWeek = "Thursday",
                            DishName = "Paneer Curry with Rice",
                            MealType = "Lunch",
                            Price = 75m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2843),
                            DayOfWeek = "Thursday",
                            DishName = "Khichdi",
                            MealType = "Dinner",
                            Price = 40m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2845),
                            DayOfWeek = "Friday",
                            DishName = "Chicken Curry",
                            MealType = "Lunch",
                            Price = 100m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2856),
                            DayOfWeek = "Friday",
                            DishName = "Egg Curry with Rice",
                            MealType = "Dinner",
                            Price = 70m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2858),
                            DayOfWeek = "Saturday",
                            DishName = "Special Thali",
                            MealType = "Lunch",
                            Price = 120m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2863),
                            DayOfWeek = "Saturday",
                            DishName = "Pulao",
                            MealType = "Dinner",
                            Price = 65m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2866),
                            DayOfWeek = "Sunday",
                            DishName = "Fish Curry",
                            MealType = "Lunch",
                            Price = 110m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 2, 11, 50, 17, 927, DateTimeKind.Utc).AddTicks(2868),
                            DayOfWeek = "Sunday",
                            DishName = "Mixed Veg Rice",
                            MealType = "Dinner",
                            Price = 55m
                        });
                });

            modelBuilder.Entity("MessManagement.Models.Attendance", b =>
                {
                    b.HasOne("MessManagement.Models.User", "MarkedByUser")
                        .WithMany()
                        .HasForeignKey("MarkedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarkedByUser");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagement.Models.Member", b =>
                {
                    b.HasOne("MessManagement.Models.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("MessManagement.Models.Member", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.PasswordHistory", b =>
                {
                    b.HasOne("MessManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.PasswordResetToken", b =>
                {
                    b.HasOne("MessManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MessManagement.Models.Payment", b =>
                {
                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagement.Models.Suggestion", b =>
                {
                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessManagement.Models.User", "RespondedByUser")
                        .WithMany()
                        .HasForeignKey("RespondedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Member");

                    b.Navigation("RespondedByUser");
                });

            modelBuilder.Entity("MessManagement.Models.WaterTea", b =>
                {
                    b.HasOne("MessManagement.Models.Member", "Member")
                        .WithMany("WaterTeaRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagement.Models.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");

                    b.Navigation("WaterTeaRecords");
                });

            modelBuilder.Entity("MessManagement.Models.User", b =>
                {
                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
